package org.mjard.maven.jar.deployer.utils;

/**
 * The Interface Constants.
 *
 * @author Luis Eduardo Ferro Diez
 */
public interface Constants {

	/** The generated pom description. */
	String GENERATED_POM_DESCRIPTION = "Generated by maven-jar-deployer.";
	
	/** The model version. */
	String MODEL_VERSION = "4.0.0";
	
	/** The example pom description. */
	String EXAMPLE_POM_DESCRIPTION = "Example pom containing all the references of all the exported jars";
	
	/** The missing arg message. */
	String MISSING_ARG_MESSAGE = "The argument(s) {0} is/are missing...";
	
	/** The unrecognized arg message. */
	String INVALID_ARG_MESSAGE = "The argument {0} is not valid.";
	
}
